# Generated by Django 4.0 on 2022-01-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
