# Generated by Django 4.0 on 2022-01-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_info_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='phone',
            field=models.IntegerField(default=1, max_length=11),
        ),
    ]
