# Generated by Django 4.0 on 2022-01-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_info_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.IntegerField(max_length=11),
        ),
    ]
