# Generated by Django 4.0 on 2022-01-10 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(default=1, upload_to='upload/'),
            preserve_default=False,
        ),
    ]
