# Generated by Django 4.0 on 2022-01-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_products_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='phone',
        ),
        migrations.AddField(
            model_name='info',
            name='con_password',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
